name: macos-build

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Add micromamba to system path
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-name: appladmix
        activate-environment: appladmix
        environment-file: environment.yml

