name: macos-build

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Add micromamba to system path
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-name: ineal
        activate-environment: ineal
        environment-file: environment.yml
    - name: Test bcftools
      run: |
        cd ./notebooks/vcf
        micromamba run -n ineal bcftools view ./data/chr21.YRI.CEU.vcf.gz -S ./data/YRI.list | micromamba run -n ineal bgzip -c > chr21.YRI.vcf.gz
        cd ../..

